workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      android_signing:
        - keystore: androis_sign

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Android - Set up key.properties
        script: |
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF

      - name: Android - Build signed APK
        script: |
          flutter build apk --release \
            --build-name=1.0.0 \
            --build-number=1

      - name: Android - Build signed AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.0 \
            --build-number=1

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
