workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: Apintie_


    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.viastreaming.apintie
      vars:
        APP_ID: 6808a9a516c8016a03253f44 # <-- Put your APP ID here
      flutter: stable
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
      android_signing:
        keystore: androis_sign
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Install Flutter dependencies
        script: |
          flutter clean
          rm -rf ios/Podfile.lock ios/Pods
          flutter pub get

      - name: iOS - Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Flutter build ipa and automatic versioning
        script: |
          # See the following link about getting the latest App Store or TestFlight version - https://docs.codemagic.io/knowledge-codemagic/build-versioning/#app-store-or-testflight-latest-build-number
          flutter build ipa --release \
            --build-name=5.0.8 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - janibulhoquesyeam@gmail.com.com
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      slack:
        # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
        channel: "#builds"
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: false
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - App Store Connect Users
          - Apintie 2.0.0 Testers

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false