workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS Simulator .app
        script: |
          flutter build ios --debug --simulator

    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - janibulhoquesyeam@gmail.com
        notify:
          success: true
          failure: false
      slack:
        channel: "#builds"
        notify_on_build_start: true
        notify:
          success: true
          failure: false
