workflows:
  ios-android-build:
    name: Build iOS IPA and Android APK
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter clean
          rm -rf ios/Podfile.lock ios/Pods
          flutter pub get

      - name: iOS - Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build iOS IPA
        script: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          cd Payload
          zip -r ../app.ipa .
          cd ..
          rm -rf Payload

      - name: Build Android APK
        script: |
          flutter build apk --release
          cp build/app/outputs/flutter-apk/app-release.apk app.apk

    artifacts:
      - app.ipa
      - app.apk
