workflows:
  ios-build:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          rm -rf ios/Podfile.lock ios/Pods
          flutter pub get
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          cd Payload
          zip -r ../app.ipa .
    artifacts:
      - app.ipa
