workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build iOS Simulator .app
        script: |
          flutter build ios --debug --simulator

    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true
